// <auto-generated />
using System;
using DnDCharacterTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DnDCharacterTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DnDCharacterTracker.Models.AbilityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AbilityScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Strenght"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wisdom"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Intelligence"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Charisma"
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Charisma");

                    b.Property<int>("Constitution");

                    b.Property<int>("Dexterity");

                    b.Property<int>("FK_Race");

                    b.Property<int>("Intelligence");

                    b.Property<string>("Name");

                    b.Property<int>("Strenght");

                    b.Property<int>("Wisdom");

                    b.HasKey("Id");

                    b.HasIndex("FK_Race");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterAbilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_AbilityScore");

                    b.Property<int>("FK_Character");

                    b.HasKey("Id");

                    b.HasIndex("FK_AbilityScore");

                    b.HasIndex("FK_Character");

                    b.ToTable("CharacterAbilities");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Character");

                    b.Property<int>("FK_Class");

                    b.Property<int>("Level");

                    b.HasKey("Id");

                    b.HasIndex("FK_Character");

                    b.HasIndex("FK_Class");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Character");

                    b.Property<int>("FK_Proficiency");

                    b.HasKey("Id");

                    b.HasIndex("FK_Character");

                    b.HasIndex("FK_Proficiency");

                    b.ToTable("CharacterProficiencies");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterRaceFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Character");

                    b.Property<int>("FK_RaceFeature");

                    b.HasKey("Id");

                    b.HasIndex("FK_Character");

                    b.HasIndex("FK_RaceFeature");

                    b.ToTable("CharacterRaceFeatures");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Character");

                    b.Property<int>("FK_Skill");

                    b.HasKey("Id");

                    b.HasIndex("FK_Character");

                    b.HasIndex("FK_Skill");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllowedOptions");

                    b.Property<string>("Descriminator");

                    b.HasKey("Id");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedOptions = 1,
                            Descriminator = "RacialLanguage"
                        },
                        new
                        {
                            Id = 3,
                            AllowedOptions = 1,
                            Descriminator = "RacialProficiency"
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharacterId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Not chosen yet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fighter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Paladin"
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.ClassAbilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_AbilityScore");

                    b.Property<int>("FK_Class");

                    b.HasKey("Id");

                    b.HasIndex("FK_AbilityScore");

                    b.HasIndex("FK_Class");

                    b.ToTable("ClassAbilities");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.ClassFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Class");

                    b.Property<int>("FK_Feature");

                    b.Property<int>("Level");

                    b.HasKey("Id");

                    b.HasIndex("FK_Class");

                    b.HasIndex("FK_Feature");

                    b.ToTable("ClassFeatures");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllowedNumberOfChoices");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.FeatureChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Feature");

                    b.Property<int>("FK_Option");

                    b.HasKey("Id");

                    b.HasIndex("FK_Feature");

                    b.HasIndex("FK_Option");

                    b.ToTable("FeatureChoices");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("FK_Choice");

                    b.Property<string>("Name");

                    b.Property<bool>("free");

                    b.HasKey("Id");

                    b.HasIndex("FK_Choice");

                    b.ToTable("Option");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_Choice = 1,
                            Name = "Infernal",
                            free = false
                        },
                        new
                        {
                            Id = 2,
                            FK_Choice = 1,
                            Name = "Celestial",
                            free = false
                        },
                        new
                        {
                            Id = 3,
                            FK_Choice = 1,
                            Name = "Dwarvish",
                            free = false
                        },
                        new
                        {
                            Id = 4,
                            FK_Choice = 1,
                            Name = "Common",
                            free = true
                        },
                        new
                        {
                            Id = 106,
                            FK_Choice = 3,
                            Name = "Smith’s tools",
                            free = false
                        },
                        new
                        {
                            Id = 107,
                            FK_Choice = 3,
                            Name = "Brewer’s supplies",
                            free = false
                        },
                        new
                        {
                            Id = 108,
                            FK_Choice = 3,
                            Name = "Mason’s tools",
                            free = false
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Proficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Proficiencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abyssal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aquan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Auran"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Celestial"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Common"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Deep Speech"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Draconic"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Druidic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dwarvish"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Elvish"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Giant"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gnomish"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gnoll"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Halfling"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ignan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Infernal"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Primordial"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Sylvan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Undercommon"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Artisan’s Tools"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Disguise Kit"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Forgery Kit"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Gaming Set"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Herbalism Kit"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Musical Instrument"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Poisoner’s Kit"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Simple Weapons"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Martial Weapons"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Light Armor"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Medium Armor"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Simple Weapons"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Heavy Armor"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Club"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Dagger"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Greatclub"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Handaxe"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Javelin"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Light Hammer"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Mace"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Quarterstaff"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Sickle"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Spear"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Crossbow, light"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Dart"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Shortbow"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Sling"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Battleaxe"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Flail"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Greataxe"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Greatsword"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Halberd"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Lance"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Longsword"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Maul"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Morningstar"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Pike"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Rapier"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Scimitar"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Shortsword"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Trident"
                        },
                        new
                        {
                            Id = 63,
                            Name = "War Pick"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Warhammer"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Whip"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Shortsword"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Trident"
                        },
                        new
                        {
                            Id = 68,
                            Name = "War Pick"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Warhammer"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Whip"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Alchemist’s supplies"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Brewer’s supplies"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Calligrapher's Supplies"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Carpenter’s tools"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Cartographer’s tools"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Cobbler’s tools"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Cook’s utensils"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Glassblower’s tools"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Jeweler’s tools"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Leatherworker’s tools"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Mason’s tools"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Painter’s supplies"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Potter’s tools"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Smith’s tools"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Tinker’s tools"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Weaver’s tools"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Woodcarver’s tools"
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Speed");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Not chosen yet",
                            Speed = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Human",
                            Speed = 30
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dwarf",
                            Speed = 0
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceAbilityScores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_AbilityScore");

                    b.Property<int>("FK_Race");

                    b.Property<int>("amount");

                    b.HasKey("Id");

                    b.HasIndex("FK_AbilityScore");

                    b.HasIndex("FK_Race");

                    b.ToTable("raceAbilityScores");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FK_AbilityScore = 1,
                            FK_Race = 2,
                            amount = 1
                        },
                        new
                        {
                            Id = -2,
                            FK_AbilityScore = 2,
                            FK_Race = 2,
                            amount = 1
                        },
                        new
                        {
                            Id = -3,
                            FK_AbilityScore = 3,
                            FK_Race = 2,
                            amount = 1
                        },
                        new
                        {
                            Id = -4,
                            FK_AbilityScore = 4,
                            FK_Race = 2,
                            amount = 1
                        },
                        new
                        {
                            Id = -5,
                            FK_AbilityScore = 5,
                            FK_Race = 2,
                            amount = 1
                        },
                        new
                        {
                            Id = -6,
                            FK_AbilityScore = 6,
                            FK_Race = 2,
                            amount = 1
                        },
                        new
                        {
                            Id = -7,
                            FK_AbilityScore = 3,
                            FK_Race = 3,
                            amount = 2
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RaceFeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Your Ability Scores each increase by 1.",
                            Name = "Ability Score Increase"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Humans reach Adulthood in their late teens and live less than a century.",
                            Name = "Age"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Humans tend toward no particular Alignment. The best and the worst are found among them.",
                            Name = "Alignment"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Humans vary widely in height and build, from barely 5 feet to well over 6 feet tall. Regardless of your position in that range, your size is Medium.",
                            Name = "Size"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Your base walking speed is 30 feet.",
                            Name = "Speed"
                        },
                        new
                        {
                            Id = 6,
                            Description = "You can speak, read, and write Common and one extra language of your choice. Humans typically learn the Languages of other peoples they deal with, including obscure dialects. They are fond of sprinkling their Speech with words borrowed from other tongues: Orc curses, Elvish musical expressions, Dwarvish Military phrases, and so on.",
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 101,
                            Description = "Your Constitution score increases by 2.",
                            Name = "Ability Score Increase"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Dwarves mature at the same rate as Humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.",
                            Name = "Age"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Most Dwarves are lawful, believing firmly in the benefits of a well-ordered society. They tend toward good as well, with a strong sense of Fair Play and a belief that everyone deserves to share in the benefits of a just order.",
                            Name = "Alignment"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.",
                            Name = "Size"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Your base walking speed is 25 feet. Your speed is not reduced by wearing Heavy Armor.",
                            Name = "Speed"
                        },
                        new
                        {
                            Id = 106,
                            Description = "Accustomed to life Underground, you have superior vision in dark and dim Conditions. You can see in dim light within 60 feet of you as if it were bright light, and in Darkness as if it were dim light. You can’t discern color in Darkness, only Shades of Gray.",
                            Name = "Darkvision"
                        },
                        new
                        {
                            Id = 107,
                            Description = "You have advantage on Saving Throws against poison, and you have Resistance against poison damage.",
                            Name = "Dwarven Resilience"
                        },
                        new
                        {
                            Id = 108,
                            Description = " You have proficiency with the Battleaxe, Handaxe, Light Hammer, and Warhammer.",
                            Name = "Dwarven Combat Training"
                        },
                        new
                        {
                            Id = 109,
                            Description = "You gain proficiency with the artisan’s tools of your choice: smith’s tools, brewer’s supplies, or mason’s tools.",
                            Name = "Tool Proficiency"
                        },
                        new
                        {
                            Id = 110,
                            Description = "Whenever you make an Intelligence (History) check related to the Origin of stonework, you are considered proficient in the History skill and add double your Proficiency Bonus to the check, instead of your normal Proficiency Bonus.",
                            Name = "Stonecunning"
                        },
                        new
                        {
                            Id = 111,
                            Description = "You can speak, read, and write Common and Dwarvish. Dwarvish is full of hard consonants and guttural sounds, and those characteristics spill over into whatever other language a dwarf might speak.",
                            Name = "Languages"
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceFeatureChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Choice");

                    b.Property<int>("FK_RaceFeature");

                    b.HasKey("Id");

                    b.HasIndex("FK_Choice");

                    b.HasIndex("FK_RaceFeature");

                    b.ToTable("RaceFeatureChoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_Choice = 1,
                            FK_RaceFeature = 6
                        },
                        new
                        {
                            Id = 109,
                            FK_Choice = 3,
                            FK_RaceFeature = 109
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceProficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Proficiency");

                    b.Property<int>("FK_Race");

                    b.HasKey("Id");

                    b.HasIndex("FK_Proficiency");

                    b.HasIndex("FK_Race");

                    b.ToTable("RaceProficiencies");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            FK_Proficiency = 49,
                            FK_Race = 3
                        },
                        new
                        {
                            Id = 102,
                            FK_Proficiency = 38,
                            FK_Race = 3
                        },
                        new
                        {
                            Id = 103,
                            FK_Proficiency = 40,
                            FK_Race = 3
                        },
                        new
                        {
                            Id = 104,
                            FK_Proficiency = 69,
                            FK_Race = 3
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceRacefeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Race");

                    b.Property<int>("FK_RaceFeature");

                    b.HasKey("Id");

                    b.HasIndex("FK_Race");

                    b.HasIndex("FK_RaceFeature");

                    b.ToTable("RaceRacefeatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_Race = 2,
                            FK_RaceFeature = 1
                        },
                        new
                        {
                            Id = 2,
                            FK_Race = 2,
                            FK_RaceFeature = 2
                        },
                        new
                        {
                            Id = 3,
                            FK_Race = 2,
                            FK_RaceFeature = 3
                        },
                        new
                        {
                            Id = 4,
                            FK_Race = 2,
                            FK_RaceFeature = 4
                        },
                        new
                        {
                            Id = 5,
                            FK_Race = 2,
                            FK_RaceFeature = 5
                        },
                        new
                        {
                            Id = 6,
                            FK_Race = 2,
                            FK_RaceFeature = 6
                        },
                        new
                        {
                            Id = 101,
                            FK_Race = 3,
                            FK_RaceFeature = 101
                        },
                        new
                        {
                            Id = 102,
                            FK_Race = 3,
                            FK_RaceFeature = 102
                        },
                        new
                        {
                            Id = 103,
                            FK_Race = 3,
                            FK_RaceFeature = 103
                        },
                        new
                        {
                            Id = 104,
                            FK_Race = 3,
                            FK_RaceFeature = 104
                        },
                        new
                        {
                            Id = 105,
                            FK_Race = 3,
                            FK_RaceFeature = 105
                        },
                        new
                        {
                            Id = 106,
                            FK_Race = 3,
                            FK_RaceFeature = 106
                        },
                        new
                        {
                            Id = 107,
                            FK_Race = 3,
                            FK_RaceFeature = 107
                        },
                        new
                        {
                            Id = 108,
                            FK_Race = 3,
                            FK_RaceFeature = 108
                        },
                        new
                        {
                            Id = 109,
                            FK_Race = 3,
                            FK_RaceFeature = 109
                        },
                        new
                        {
                            Id = 110,
                            FK_Race = 3,
                            FK_RaceFeature = 110
                        },
                        new
                        {
                            Id = 111,
                            FK_Race = 3,
                            FK_RaceFeature = 111
                        });
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_AbilityScore");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("FK_AbilityScore");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FK_AbilityScore = 2,
                            Name = "Acrobatics"
                        },
                        new
                        {
                            Id = 2,
                            FK_AbilityScore = 4,
                            Name = "Animal handling"
                        },
                        new
                        {
                            Id = 3,
                            FK_AbilityScore = 5,
                            Name = "Arcana"
                        },
                        new
                        {
                            Id = 4,
                            FK_AbilityScore = 1,
                            Name = "Athletics"
                        },
                        new
                        {
                            Id = 5,
                            FK_AbilityScore = 6,
                            Name = "Deception"
                        },
                        new
                        {
                            Id = 6,
                            FK_AbilityScore = 5,
                            Name = "History"
                        },
                        new
                        {
                            Id = 7,
                            FK_AbilityScore = 4,
                            Name = "Insight"
                        },
                        new
                        {
                            Id = 8,
                            FK_AbilityScore = 6,
                            Name = "Intimidation"
                        },
                        new
                        {
                            Id = 9,
                            FK_AbilityScore = 4,
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = 10,
                            FK_AbilityScore = 5,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 11,
                            FK_AbilityScore = 4,
                            Name = "Perception"
                        },
                        new
                        {
                            Id = 12,
                            FK_AbilityScore = 6,
                            Name = "Performance"
                        },
                        new
                        {
                            Id = 13,
                            FK_AbilityScore = 6,
                            Name = "Persuasion"
                        },
                        new
                        {
                            Id = 14,
                            FK_AbilityScore = 5,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 15,
                            FK_AbilityScore = 2,
                            Name = "Sleight of Hand"
                        },
                        new
                        {
                            Id = 16,
                            FK_AbilityScore = 2,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 17,
                            FK_AbilityScore = 4,
                            Name = "Survival"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Character", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("FK_Race")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterAbilities", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.AbilityScore", "AbilityScore")
                        .WithMany()
                        .HasForeignKey("FK_AbilityScore")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("FK_Character")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterClass", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("FK_Character")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("FK_Class")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterProficiency", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("FK_Character")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Proficiency", "Proficiency")
                        .WithMany()
                        .HasForeignKey("FK_Proficiency")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterRaceFeature", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("FK_Character")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.RaceFeature", "RaceFeature")
                        .WithMany()
                        .HasForeignKey("FK_RaceFeature")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.CharacterSkill", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("FK_Character")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("FK_Skill")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Class", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Character")
                        .WithMany("Classes")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.ClassAbilities", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.AbilityScore", "AbilityScore")
                        .WithMany()
                        .HasForeignKey("FK_AbilityScore")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("FK_Class")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.ClassFeature", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("FK_Class")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FK_Feature")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.FeatureChoice", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FK_Feature")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Option", "Option")
                        .WithMany()
                        .HasForeignKey("FK_Option")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Option", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Choice", "Choice")
                        .WithMany("AvailableOptions")
                        .HasForeignKey("FK_Choice")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceAbilityScores", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.AbilityScore", "AbilityScore")
                        .WithMany()
                        .HasForeignKey("FK_AbilityScore")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("FK_Race")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceFeatureChoice", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("FK_Choice")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.RaceFeature", "RaceFeature")
                        .WithMany()
                        .HasForeignKey("FK_RaceFeature")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceProficiency", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Proficiency", "Proficiency")
                        .WithMany()
                        .HasForeignKey("FK_Proficiency")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.Character", "Race")
                        .WithMany()
                        .HasForeignKey("FK_Race")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.RaceRacefeature", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("FK_Race")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DnDCharacterTracker.Models.RaceFeature", "RaceFeature")
                        .WithMany()
                        .HasForeignKey("FK_RaceFeature")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DnDCharacterTracker.Models.Skill", b =>
                {
                    b.HasOne("DnDCharacterTracker.Models.AbilityScore", "AbilityScore")
                        .WithMany()
                        .HasForeignKey("FK_AbilityScore")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
